# Generated by Django 5.2.8 on 2025-11-16 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesAdicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('tipoSanguineo', models.CharField(blank=True, max_length=2, null=True)),
                ('alergiasMedicamentos', models.TextField(blank=True, null=True)),
                ('restricoes', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContatosEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEmergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefoneEmergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('informacoes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contatosemergencia', to='supportIdentification.informacoesadicionais')),
            ],
        ),
    ]
