# Generated by Django 5.2.8 on 2025-11-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportIdentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatosemergencia',
            name='informacoes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_emergencia', to='supportIdentification.informacoesadicionais'),
        ),
    ]
